version: "3"

services:
  mongo:
    image: mongo:4.2.2-bionic # MongoDB on Ubuntu Bionic
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: test
    ports:
      - "27017:27017"
    volumes:
      - ./_docker_compose_volumes/mongoData:/data/db
  rabbitmq:
    image: rabbitmq:3.8.2-management-alpine # RabbitMQ on alpine with dashboard UI
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # dashboard UI port (http://localhost:15672/) - default user/pass is guest/guest
    volumes:
      - ./_docker_compose_volumes/rabbitmqData:/var/lib/rabbitmq
  # web:
  #   image: rooknj/prysmalight-web:1.1.0
  #   container_name: web
  #   restart: always
  #   ports:
  #     - "80:80"   
  # apiGateway:
  #   image: rooknj/prysmalight-web:1.1.0
  #   container_name: apiGateway
  #   restart: always
  #   ports:
  #     - "4001:4001"   
  # backend:
  #   image: rooknj/prysmalight-web:1.1.0
  #   container_name: backend
  #   restart: always
  #   ports:
  #     - "4002:4002" 
