version: '3'

networks:
  kong-net:
    driver: bridge
  database-net:
    driver: bridge

services:
  # Front-end Web Service
  # ---
  web:
    image: virtuoso-web:latest
    container_name: virtuoso_web_service
    restart: always
    environment:
      FOO: bar
    ports:
      - '80:80'
  # API Gateway
  # (kong w/o database)
  # ---
  api_gateway:
    image: virtuoso-api-gateway:latest
    container_name: virtuoso-api-gateway
    restart: always
    ports:
      - '8000:8000'
      - '8001:8001' # Remove this for production
    networks:
      - kong-net
  # Auth Service
  # ---
  auth:
    #build: ../
    image: virtuoso-auth:latest
    container_name: virtuoso_auth_service
    hostname: virtuoso_auth_service
    restart: always
    environment:
      MONGODB_URI: mongodb://root:root@mongo_service:27017/test
      JWT_SECRET: test123
    ports:
      - '4000:4000'
    networks:
      - kong-net
      - database-net
    depends_on:
      - mongo
      - api_gateway
  # MongoDB
  # ---
  mongo:
    image: mongo:4.2.2-bionic # MongoDB on Ubuntu Bionic
    container_name: mongo_service
    hostname: mongo_service
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: test
    ports:
      - '27017:27017'
    networks:
      - database-net
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro # this works so we're keeping it
      - ./_docker_compose_volumes/mongoData:/data/db